services:
  - type: web
    name: fastapi-url-shortener
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: MONGODB_URI
        value: mongodb://user:password@host:27017
      - key: MONGODB_DB
        value: shortener
